(()=>{
const statements={anyone:'I’m Jamie, an AI-native product designer turning complex systems into clear, useful experiences.',recruiters:'I design AI products, growth journeys, and research-led systems, and make the impact easy to scan.',leaders:'I turn research signals into product direction, interaction systems, and decisions teams can ship.',builders:'I work with product and engineering to turn messy AI workflows into focused, buildable experiences.'};
const group=document.querySelector('.audience-switcher'),copy=document.querySelector('[data-audience-copy]'),title=document.querySelector('#home-title'),buttons=[...group.querySelectorAll('button')],reduce=matchMedia('(prefers-reduced-motion:reduce)');
let active='';const glider=document.createElement('span');glider.className='audience-glider';glider.setAttribute('aria-hidden','true');group.prepend(glider);
function move(){const button=buttons.find(b=>b.dataset.audience===active);if(!button)return;glider.style.width=(button.offsetWidth-4)+'px';glider.style.height=(button.offsetHeight-12)+'px';glider.style.transform=`translate(${button.offsetLeft+2}px, ${button.offsetTop}px)`;}
function choose(key,animate=true){if(!statements[key]||key===active)return;active=key;if(animate){const url=new URL(location.href);if(key==='anyone')url.searchParams.delete('audience');else url.searchParams.set('audience',key);history.replaceState({},'',url.pathname+url.search+url.hash);}buttons.forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.audience===key)));copy.replaceChildren();if(key==='anyone'){copy.append('I’m ');const name=document.createElement('button');name.type='button';name.className='jamie-play';name.setAttribute('aria-label','Jamie');const shape=document.createElement('span');shape.className='jamie-shape';shape.setAttribute('aria-hidden','true');
[...'Jamie'].forEach((letter,index)=>{const glyph=document.createElement('span');glyph.className='jamie-letter';glyph.style.setProperty('--delay',`${index*48}ms`);glyph.style.setProperty('--rise',`${[5,7,8,6,4][index]}px`);glyph.style.setProperty('--tilt',`${[-3,-2,2,3,1][index]}deg`);if(letter==='i'){glyph.classList.add('jamie-i');const stem=document.createElement('span');stem.textContent='ı';const dot=document.createElement('span');dot.className='jamie-dot';glyph.append(stem,dot)}else glyph.textContent=letter;shape.append(glyph)});name.append(shape);
let running=false;function wave(){if(reduce.matches||running)return;running=true;name.classList.add('is-waving');setTimeout(()=>{name.classList.remove('is-waving');running=false},850)}
name.addEventListener('pointerenter',e=>{if(e.pointerType==='mouse')wave()});name.addEventListener('click',wave);name.addEventListener('focus',()=>{if(name.matches(':focus-visible'))wave()});
copy.append(name,statements[key].slice('I’m Jamie'.length));}else copy.textContent=statements[key];move();copy.getAnimations().forEach(a=>a.cancel());if(animate&&!reduce.matches)copy.animate([{opacity:.25,transform:'translateY(4px)'},{opacity:1,transform:'translateY(0)'}],{duration:220,easing:'cubic-bezier(.2,.8,.2,1)'});}
buttons.forEach(b=>b.addEventListener('click',()=>choose(b.dataset.audience)));choose(new URL(location.href).searchParams.get('audience') in statements?new URL(location.href).searchParams.get('audience'):'anyone',false);
function reserveHeight(){const selected=active;title.style.minHeight='0';const old=copy.innerHTML;let max=0;for(const value of Object.values(statements)){copy.textContent=value;max=Math.max(max,copy.getBoundingClientRect().height)}copy.innerHTML=old;active='';choose(selected||'anyone',false);title.style.minHeight=max+'px';move();}
document.fonts.ready.then(reserveHeight);let resize;window.addEventListener('resize',()=>{clearTimeout(resize);resize=setTimeout(reserveHeight,120)});new ResizeObserver(move).observe(group);
})();
